version: '3'
services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    container_name: workspace
    volumes:
      - ..:/workspace:cached
    depends_on:
      - keycloak
    network_mode: host
    command: /bin/sh -c "while sleep 1000; do :; done"
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak
    volumes:
      - keycloak:/keycloak-data
    network_mode: host
    expose:
      - 8080
    command:
      - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    tty: true
    stdin_open: true
    restart: always

volumes:
  keycloak:

networks:
  keycloak:
    driver: bridge